# Generated by Django 3.1.2 on 2021-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0011_tenders_file_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='file_uploaded',
            field=models.FileField(default='', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='file_uploaded',
            field=models.FileField(default='', upload_to='uploads'),
        ),
    ]
